### ISSUE TITLE
Library Documentation

### ISSUE THREAD

**Issue by codematix** [vsavkin/fpdart#1]
Do you have any plans to update the documentation for the various functions and classes you have implemented?

**Comment by vsavkin** [comment]
I'll try to add some docs next week. 

But you don't have to wait for the docs to start using fpdart. The library is less than 200 lines of code, so you can just read to the source code in half an hour. Also, the readme covers most of the implemented functions (not in great detail, but enough to get started).

**Comment by codematix** [comment]
@vsavkin Thanks for the clarification.
